apiVersion: v1
kind: Service
metadata:
  name: rsvp
  labels:
    app: rsvp
spec:
  type: LoadBalancer
  ports:
  - name: tcp-5000
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: rsvp

